"""Service authentication — docs/10 §1 T1, and the three headers of §3.4.

T1: *"AI Services **chỉ nhận lời gọi từ BE C.Brain**. Mọi lời gọi không qua xác
thực dịch vụ đều bị từ chối. Cách xác thực (mTLS, khoá dịch vụ, chính sách
mạng) do hạ tầng chọn."*

This module implements the *khoá dịch vụ* option: a shared secret in a header.
The comparison is constant-time, and a caller that fails it learns nothing
beyond "no" (see `errors.MESSAGE_UNAUTHENTICATED`).

──────────────────────────────────────────────────────────────────────────
Where the secret lives, and why it is not in `config/*.yaml`
──────────────────────────────────────────────────────────────────────────

The secret itself is an environment variable, never a file in the repo and
never a literal in code. The NAME of that variable is `SERVICE_KEY_ENV_VAR`
below, and `.env.example` documents it next to the other deployment
parameters.

That placement follows T1's own words — *"Cách xác thực ... do hạ tầng chọn"*.
The three config groups (07 Mục 3.1/3.3) are the embedding contract and the
nine tuning parameters; `.env.example` states its own scope in the same terms:
*"Tham số KẾT NỐI hạ tầng — KHÔNG phải ba nhóm cấu hình"*, deployment values
that differ per customer install (R6). A service key is exactly that, and it
differs per install for the same reason the database password does.

⚠️ This is a decision PO must confirm — it is reported as an escalation. If PO
prefers the variable's NAME to come from a config key instead, nothing in this
package changes: `app.build_app` takes `service_key_env_var` as a required
argument with no default, so only the composition root moves.

⛔ What is NOT negotiable either way: a missing variable is a REFUSAL TO START,
naming the variable (CLAUDE.md Mục 4 quy tắc 2). A service that boots with an
empty secret would either reject every call or — far worse, if the comparison
were written carelessly — accept every call with an empty header.
"""

from __future__ import annotations

import hmac
from collections.abc import Mapping
from typing import Final

__all__ = [
    "IDEMPOTENCY_KEY_HEADER",
    "REQUEST_ID_HEADER",
    "SERVICE_KEY_ENV_VAR",
    "SERVICE_KEY_HEADER",
    "ServiceKeyNotConfigured",
    "presented_key_matches",
    "resolve_service_key",
]


#: docs/10 §1 T1 — the service credential. Not a user token: it says *"this is
#: Backend"*, never *"this is a person"* (T2 keeps people on Backend's side).
SERVICE_KEY_HEADER: Final = "X-Service-Key"

#: docs/10 §3.4 — *"Mọi lời gọi mang `X-Request-Id`, AI ghi kèm vào nhật ký của
#: mình."* Generated by this service when Backend omits it, and always echoed.
REQUEST_ID_HEADER: Final = "X-Request-Id"

#: docs/10 §3.4 — *"Mọi lời gọi ghi mang header `Idempotency-Key`."*
IDEMPOTENCY_KEY_HEADER: Final = "Idempotency-Key"

#: The environment variable holding the secret. A NAME, not a value — nothing
#: in this repo ever contains the secret itself. Mirrored (with an empty value)
#: in `.env.example`, the same way `CBRAIN_PG_HOST` is.
SERVICE_KEY_ENV_VAR: Final = "CBRAIN_API_SERVICE_KEY"


class ServiceKeyNotConfigured(RuntimeError):
    """The environment variable holding the service key is absent or blank.

    Raised while the application is being BUILT, not on the first request:
    docs/10 §3.5 gives a running-but-misconfigured service `503
    SERVICE_MISCONFIGURED`, and a service whose credential never existed is
    not in that category — it must not reach the port at all.
    """


def resolve_service_key(*, env_var: str, environ: Mapping[str, str]) -> str:
    """Read the secret out of `environ`, or refuse to start.

    `environ` is passed in rather than read from `os` here so the refusal is
    testable without mutating the process — and so a deployment can feed the
    value from a secret manager without this module growing a second source.

    Raises:
        ServiceKeyNotConfigured: the variable is absent, or present and blank.
            Blank is treated as absent on purpose: an empty secret in a `.env`
            file is the shape a half-finished install has, and it must not be
            the shape that boots.
    """
    if not env_var or not env_var.strip():
        raise ServiceKeyNotConfigured(
            "No environment variable name was given for the service key. The "
            "caller of build_app must name it explicitly (docs/10 §1 T1)."
        )

    value = environ.get(env_var)
    if value is None or not value.strip():
        raise ServiceKeyNotConfigured(
            f"Environment variable {env_var!r} is missing or blank, so the "
            f"service key that authenticates Backend C.Brain does not exist. "
            f"AI Services REFUSES TO START rather than serve unauthenticated "
            f"calls (docs/10 §1 T1; CLAUDE.md Mục 4 quy tắc 2). Set it in the "
            f"deployment environment — see .env.example."
        )
    return value


def presented_key_matches(presented: str | None, *, secret: str) -> bool:
    """Constant-time comparison of the header against the configured secret.

    `hmac.compare_digest` rather than `==`: `==` returns as soon as two bytes
    differ, and the timing difference is enough to recover a secret one
    character at a time. There is no error branch for "header absent" — it
    returns `False` like any other wrong value, which is what keeps the two
    cases indistinguishable to the caller.
    """
    if presented is None:
        return False
    return hmac.compare_digest(presented, secret)
